package com.superit.smart.qa.ui.smartbox.pojo;

import lombok.Builder;
import lombok.Getter;
import org.jetbrains.annotations.NotNull;

import java.time.LocalDate;

@Getter
@Builder
public class RentedUnitWithExistingDebitorUI {

    @NotNull
    private final String building;
    private final String unitID;
    private final String shortDesignation;
    private final LocalDate unitStart;
    private final String typeOfUse;
    @NotNull
    private final String value;
    @NotNull
    private final String measureValue;
    private final String measureType;
    private final String unit;
    @NotNull
    private final String debitor;
    @NotNull
    private final String debitorId;
    private final LocalDate startDate; //This field is required, but in some cases it's autogenerated, therefore not always should be defined.
    private final boolean temporaryContract;
}
